name: erasure-impl
version: 0.1.0.0
github: "Constantine-Theocharis/erasure-impl"
license: BSD3
author: "Andr치s Kov치cs, Constantine Theocharis"
maintainer: "Constantine Theocharis"
copyright: "2019 Andr치s Kov치cs, 2025 Constantine Theocharis"
category: Language

description: "Implementations of elaboration for type theory with erasure"

default-extensions:
  - DerivingVia
  - DeriveAnyClass
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - OverloadedStrings
  - PatternSynonyms
  - StandaloneDeriving
  - Strict
  - TupleSections
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-missing-signatures
  - -Wno-unused-do-bind
  - -Wno-unused-matches

dependencies:
  - base >= 4.7 && < 5
  - containers
  - megaparsec

executables:
  explicit:
    main: Main.hs
    source-dirs: explicit
    ghc-options:
      - -O

  implicit:
    main: Main.hs
    source-dirs: implicit
    ghc-options:
      - -O
